name: TimescaleCLI CI

on: [push]

jobs:
  build:
    services:
      timescale:
        image: postgres:15-alpine
        env:
          # Defaults (not used anywhere)
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - name: Build
        run: make build

      - name: Test
        run: make test
